version: 2
jobs:
  build:
    working_directory: ~/circle
    docker:
      - image: python:3.4
      - image: mysql:5.6
        environment:
          MYSQL_ROOT_PASSWORD: rootpass
          MYSQL_DATABASE: testdb
          MYSQL_USER: user
          MYSQL_PASSWORD: pass
    steps:
      - checkout
      - run:
          name: Configure MySQL GPG Keys
          command: |
            key='A4A9406876FCBD3C456770C88C718D3B5072E1F5'; \
            export GNUPGHOME="$(mktemp -d)"; \
            gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; \
            gpg --export "$key" > /etc/apt/trusted.gpg.d/mysql.gpg; \
            rm -r "$GNUPGHOME"; \
            apt-key list > /dev/null
      - run:
          name: Install MySQL Client
          command: |
            apt-get update; \
            apt-get install -y mysql-client libmysqlclient-dev --no-install-recommends; \
            rm -rf /var/lib/apt/lists/*
      - run:
          name: Check Connection
          command: |
            mysql -h 127.0.0.1 -u user -ppass -e "SHOW TABLES;" testdb